# Generated by Django 3.2.3 on 2021-06-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='id del usuario')),
                ('nombre_usuario', models.CharField(max_length=64, verbose_name='nombre del usuario')),
                ('contraseña_usuario', models.CharField(max_length=32, verbose_name='contraseña del usuario')),
            ],
        ),
    ]
