# Generated by Django 3.2.3 on 2021-06-11 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.IntegerField(primary_key=True, serialize=False, verbose_name='id del genero')),
                ('nombre_genero', models.CharField(max_length=128, verbose_name='nombre del genero')),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id_juego', models.IntegerField(primary_key=True, serialize=False, verbose_name='id del juego')),
                ('nombre_juego', models.CharField(max_length=128, verbose_name='nombre del juego')),
                ('desarrollador_juego', models.CharField(max_length=128, verbose_name='desarrollador del juego')),
                ('precio_juego', models.DateField(verbose_name='Fecha de lanzamiento')),
                ('genero_juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.genero')),
            ],
        ),
    ]
