# Generated by Django 3.2.3 on 2021-06-11 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_genero_juego'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='genero_juego2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genero2', to='core.genero'),
        ),
        migrations.AddField(
            model_name='juego',
            name='genero_juego3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genero3', to='core.genero'),
        ),
        migrations.AddField(
            model_name='juego',
            name='genero_juego4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genero4', to='core.genero'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='genero_juego',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genero1', to='core.genero'),
        ),
    ]
