# Generated by Django 3.2.3 on 2021-06-11 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210610_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id_editor', models.IntegerField(primary_key=True, serialize=False, verbose_name='id del editor')),
                ('nombre_editor', models.CharField(max_length=128, verbose_name='nombre del editor')),
            ],
            options={
                'verbose_name_plural': 'Editores',
            },
        ),
        migrations.AlterModelOptions(
            name='desarrollador',
            options={'verbose_name_plural': 'Desarrolladores'},
        ),
        migrations.AlterField(
            model_name='juego',
            name='desarrollador_juego',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.desarrollador'),
        ),
        migrations.AddField(
            model_name='juego',
            name='editor_juego',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.editor'),
        ),
    ]
