# Generated by Django 3.2.3 on 2021-06-15 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210610_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='desc_juego',
            field=models.CharField(default='none', max_length=700, verbose_name='descripcion del juego'),
        ),
        migrations.AddField(
            model_name='juego',
            name='imagen_juego',
            field=models.ImageField(default='static/core/img/default.png', upload_to='', verbose_name='imagen del juego'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='genero_juego',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genero1', to='core.genero'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='genero_juego2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genero2', to='core.genero'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='genero_juego3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genero3', to='core.genero'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='genero_juego4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genero4', to='core.genero'),
        ),
    ]
