# Generated by Django 3.2.3 on 2021-06-16 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210615_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='imagen_juego',
        ),
    ]
