# Generated by Django 3.2.3 on 2021-06-16 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210616_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='carouse2',
            new_name='carousel2',
        ),
        migrations.RenameField(
            model_name='juego',
            old_name='carouse3',
            new_name='carousel3',
        ),
        migrations.RenameField(
            model_name='juego',
            old_name='carouse4',
            new_name='carousel4',
        ),
    ]
