# Generated by Django 3.2.3 on 2021-06-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210616_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='carousel',
            field=models.ImageField(default='static/core/img/default.png', upload_to='core', verbose_name='carousel1'),
        ),
        migrations.AddField(
            model_name='juego',
            name='carousel2',
            field=models.ImageField(default='static/core/img/default.png', upload_to='core', verbose_name='carousel2'),
        ),
        migrations.AddField(
            model_name='juego',
            name='carousel3',
            field=models.ImageField(default='static/core/img/default.png', upload_to='core', verbose_name='carousel3'),
        ),
        migrations.AddField(
            model_name='juego',
            name='carousel4',
            field=models.ImageField(default='static/core/img/default.png', upload_to='core', verbose_name='carousel4'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='fecha_juego',
            field=models.DateField(null=True, verbose_name='fecha de lanzamiento'),
        ),
    ]
