# Generated by Django 3.2.3 on 2021-06-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210616_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='fecha_juego',
            field=models.DateField(default='2020-01-01', null=True, verbose_name='fecha de lanzamiento'),
        ),
    ]
