# Generated by Django 3.2.3 on 2021-06-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210616_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='juego destacado'),
        ),
        migrations.AddField(
            model_name='juego',
            name='ventas_juego',
            field=models.IntegerField(default=0, verbose_name='ventas del juego'),
        ),
    ]
