# Generated by Django 3.2.3 on 2021-06-26 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210619_2009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
